packages:
  - name: default
    functions:
      - name: serverless_handler
        main: serverless_handler:app
        runtime: python:3.11
        web: true
        limits:
          timeout: 60000      # 60 seconds
          memory: 512         # 512 MB
        environment:
          FUNCTION_TYPE: stream-extractor
          PYTHONUNBUFFERED: "1"
          YT_DLP_PATH: /usr/local/bin/yt-dlp
          LOG_DIR: /tmp/proxyLogs
          REQUEST_TIMEOUT: "45"
          COOKIES_FILE: /tmp/cookies.txt

      - name: hello
        main: hello:main
        runtime: python:3.11
        web: true
        limits:
          timeout: 10000
          memory: 128
        environment:
          DESCRIPTION: "Simple health/test function"
