name: youtube-stream-url
description: YouTube stream URL extraction serverless function

packages:
  - name: default
    environment:
      PYTHONUNBUFFERED: "1"
      YT_DLP_PATH: /usr/local/bin/yt-dlp
      LOG_DIR: /tmp/proxyLogs
      REQUEST_TIMEOUT: "45"
      COOKIES_FILE: /tmp/cookies.txt
    
    functions:
      - name: stream-extractor
        main: serverless_handler:app
        runtime: python:3.11
        web: true
        limits:
          timeout: 60000      # 60 seconds
          memory: 512         # 512 MB
        environment:
          FUNCTION_TYPE: stream-extractor
